ktor:
    development: true
    deployment:
        port: 8080
    watch:
        - classes
        - resources
    application:
        modules:
            - ru.otus.otuskotlin.crypto.trade.app.ApplicationKt.module
    logger: logback

cryptotrade:
    repository:
        test: "inmemory"
        prod: "$DB_TYPE_PROD:inmemory"

        cassandra:
            hosts: localhost
            keyspace: test_keyspace
            pass: cassandra
            port: 9042
            user: cassandra